# file: .github/workflows/push-check.yml
name: push-check
# on – определяет события, которые запускают воркфлоу
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - run: python -m pip install flake8
      - name: run linter
        run: make lint
